config/routes.rb
Rails.application.routes.draw do

  devise_scope :customer do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  # 顧客側ルーティング
  scope module: :public do
    scope '/customers' do
      get 'my_page/:id' => 'customers#show', as: 'mypage'
      get 'list' => 'customers#index', as: 'list'
      get 'information/edit' => 'customers#edit', as: 'edit_information'
      patch 'information' => 'customers#update', as: 'update_information'
      get 'unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
      patch 'withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    end

    resources :customers, only: [] do
      get :followings
      get :followers
      resource :relationships, only: [:create, :destroy]
      resources :favorites, only: [:index]
    end

    resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    post 'chats' => 'chats#create'
    get 'chats/room/:id' => 'chats#show', as: 'chat'
    get 'search', to: 'searches#search'
    resources :notifications, only: [:update]
  end

  # 管理者側ルーティング
  namespace :admin do
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :customers, only: [:index, :show, :edit, :update]
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  has_many :customer_rooms
  has_many :chats
  has_many :rooms, through: :customer_rooms
  has_many :view_counts, dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_one_attached :profile_image

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(customer)
    relationships.create(followed_id: customer.id)
  end

  def unfollow(customer)
    relationships.find_by(followed_id: customer.id).destroy
  end

  def following?(customer)
    followings.include?(customer)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Customer.where(name: content)
    elsif method == 'forward'
      Customer.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      Customer.where('name LIKE ?', '%' + content)
    else
      Customer.where('name LIKE ?', '%' + content + '%')
    end
  end


  def customer_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end

  def active_for_authentication?
    super && (is_active == true)
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end

  def guest_customer?
    email == GUEST_USER_EMAIL
  end

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :email, presence: true

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).order(created_at: :desc)
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.page(params[:page])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      if @customer.is_active == false
        redirect_to admin_customer_path(@customer), notice: '会員情報が更新されました。'
      else
        redirect_to admin_customer_path(@customer), notice: '会員情報が更新されました。'
      end
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :profile_image, :is_active)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_index.html.erb
<table class="table">
    <thead class="thead-dark">
      <tr class="text-center">
        <th>会員ID</th>
        <th>アイコン</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
  <% customers.each do |customer| %>
    <% next if customer.guest_customer? %>
      <tbody>
        <tr class="text-center">
          <td><%= customer.id %></td>
          <td><%= image_tag customer.get_profile_image, class: "rounded-circle", size: '50x50' %></td>
          <td><%= link_to customer.name, admin_customer_path(customer), class: 'text-dark' %></td>
          <td><%= customer.email %></td>
          <td><%= customer.customer_status %></td>
        </tr>
      </tbody>
  <% end %>
</table>
<div class="d-flex justify-content-center">
  <%= paginate customers %>
</div>

app/views/admin/customers/_info.html.erb
<table class="table">
  <tr>
    <td>会員ID</td>
    <td><%= customer.id %></td>
  </tr>

  <tr>
    <td>アイコン</th>
    <td><%= image_tag customer.get_profile_image, class: "rounded-circle", size:'100x100' %></td>
  </tr>

  <tr>
    <td>氏名</td>
    <td><%= customer.name %></td>
  </tr>

  <tr>
    <td>メールアドレス</th>
    <td><%= customer.email %></td>
  </tr>

  <tr>
    <td>会員ステータス</th>
    <td><%= customer.customer_status %></td>
  </tr>
</table>
<div class="d-flex justify-content-center">
  <%= link_to "会 員 編 集", edit_admin_customer_path(customer), class:"btn btn-success px-5" %>
</div>

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="py-5">
      <h4 class="text-center mb-4"><%= @customer.name %>さんの会員情報編集</h4>
      <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
        <%= render "admin/shared/error_messages", resource: @customer %>
          <table class="table table-borderless d-flex justify-content-center">
            <tr>
              <td>会員ID</td>
            </tr>
            <tr>
              <td><%= @customer.id %></td>
            </tr>

            <tr>
              <td><%= f.label :profile_image, "アイコン" %></td>
            </tr>
            <tr>
              <td><%= f.file_field :profile_image, class: "form-control-file customer_image", accept: 'image/*' %></td>
            </tr>

            <tr>
              <td><%= f.label :name, "氏名" %></td>
            </tr>
            <tr>
              <td><%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "山田花子" %></td>
            </tr>

            <tr>
              <td><%= f.label :email, "メールアドレス" %></td>
            </tr>
            <tr>
              <td><%= f.text_field :email, :size=>"40", autocomplete: "email", placeholder: "sample@example.com" %></td>
            </tr>

            <tr>
              <td>会員ステータス</td>
            </tr>
            <tr>
              <td>
                <%= f.radio_button :is_active, :true %>
                <%= f.label :is_active, "有効", { value: :true }  %>

                <%= f.radio_button :is_active, :false %>
                <%= f.label :is_active, "退会", { value: :false } %>
              </td>
            </tr>
          </table>
          <div class="d-flex justify-content-center">
            <%= f.submit "編集変更を保存", class:"btn btn-success" %>
            <%= link_to '会員詳細へ戻る', admin_customer_path(@customer), class: "btn btn-secondary ml-2" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-8">
      <h3 class="text-center my-4">会員一覧</h3>
        <%= render 'index', customers: @customers%>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class='col-5'>
      <h4 class="my-4 text-center"><%= @customer.name %>さんの会員詳細</h4>
        <%= render 'info', customer: @customer %>
    </div>
  </div>

  <div class="row d-flex justify-content-center my-4">
    <div class='col-8'>
      <h3 class="text-center">投稿一覧</h3>
        <%= render "admin/posts/index", posts: @posts %>
    </div>
  </div>
  <div class="row d-flex justify-content-center my-4">
    <%= link_to '会員一覧へ戻る', admin_customers_path, class: "btn btn-secondary" %>
  </div>
</div>