config/routes.rb
Rails.application.routes.draw do

  devise_scope :customer do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  # 顧客側ルーティング
  scope module: :public do
    scope '/customers' do
      get 'my_page/:id' => 'customers#show', as: 'mypage'
      get 'list' => 'customers#index', as: 'list'
      get 'information/edit' => 'customers#edit', as: 'edit_information'
      patch 'information' => 'customers#update', as: 'update_information'
      get 'unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
      patch 'withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    end

    resources :customers, only: [] do
      get :followings
      get :followers
      resource :relationships, only: [:create, :destroy]
      resources :favorites, only: [:index]
    end

    resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    post 'chats' => 'chats#create'
    get 'chats/room/:id' => 'chats#show', as: 'chat'
    get 'search', to: 'searches#search'
    resources :notifications, only: [:update]
  end

  # 管理者側ルーティング
  namespace :admin do
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :customers, only: [:index, :show, :edit, :update]
  end


end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :customer
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy

  after_create do
    customer.followers.each do |follower|
      notifications.create(customer_id: follower.id)
    end
  end

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(title: content)
    elsif method == 'forward'
      Post.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Post.where('title LIKE ?', '%'+content)
    else
      Post.where('title LIKE ?', '%'+content+'%')
    end
  end

  has_one_attached :image

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :image, presence:true

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

 before_action :authenticate_admin!

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def index
    @posts = Post.page(params[:page]).order(created_at: :desc)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_post_path(@post), notice: "投稿内容を更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_index.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr class="text-center">
      <th></th>
      <th>写真</th>
      <th>ファッション名</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% posts.each do |post| %>
      <tr class="text-center">
        <td><%= link_to admin_customer_path(post.customer_id) do %>
          <%= image_tag post.customer.get_profile_image, class: "rounded-circle", size:'50x50' %>
          <% end %>
        </td>
        <td><%= image_tag post.image, size: "100x100" %></td>
        <td><%= link_to post.title, admin_post_path(post.id), class: 'text-dark' %></td>
        <td>コメント数: <%= post.post_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-center">
  <%= paginate posts %>
</div>

app/views/admin/posts/edit.html.erb
<div class='container'>
  <div class="row d-flex justify-content-center">
    <div class='py-5'>
      <h3 class="text-center mb-4">投稿編集</h3>
      <%= form_with model: @post, url: admin_post_path(@post.id), method: :patch do |f| %>
        <%= render 'admin/shared/error_messages', resource: @post %>
          <table class="table table-borderless d-flex justify-content-center">
            <tr>
              <td><%= f.label :image, "写真" %></td>
            </tr>
            <tr>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>

            <tr>
              <td><%= f.label :title, "ファッション名" %></td>
            </tr>
            <tr>
              <td><%= f.text_field :title, rows:'5',placeholder: "ファッション名をここに", class: "w-75" %></td>
            </tr>

            <tr>
              <td><%= f.label :body, "コーディネート内容" %></td>
            </tr>
            <tr>
              <td><%= f.text_area :body, rows:'5',placeholder: "コーディネート内容をここに", class: "w-100" %></td>
            </tr>
          </table>
          <div class="d-flex justify-content-center">
            <%= f.submit "編集内容を保存", class: "btn btn-success" %>
            <%= link_to '投稿詳細へ戻る', admin_post_path(@post.id), class: "btn btn-secondary ml-2" %>
          </div>
      <% end %>
  	</div>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class='container'>
  <div class='row d-flex justify-content-center'>
    <div class='col-8'>
      <h3 class="text-center my-4">投稿一覧</h3>
        <%= render "index", posts: @posts %>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class='container'>
  <div class='row-8'>
    <h3 class=" text-center mt-4">投稿詳細</h3>
      <table class="table table-borderless d-flex justify-content-center">
        <tr>
          <td class="text-center">
            <%= link_to admin_customer_path(@post.customer_id), class: 'text-dark' do %>
                <%= image_tag @post.customer.get_profile_image, class: "rounded-circle", size:"50x50" %><br>
                <%= @post.customer.name %>
            <% end %>
          </td>
          <td><%= image_tag @post.image, size: "300x300" %></td>
        </tr>
      </table>

      <table class="table table-borderless d-flex justify-content-center">
        <tr>
          <td>ファッション名</td>
          <td><%= link_to @post.title, admin_post_path(@post.id), class: 'text-dark' %></td>
        </tr>
        <tr>
          <td>コーディネート内容</td>
          <td><%= @post.body %></td>
        </tr>
        <tr>
          <td>コメント数: <%= @post.post_comments.count %></td>
          <td>
            <%= link_to '編集', edit_admin_post_path(@post.id), class: "btn btn-sm btn-success px-3" %>
            <%= link_to '削除', admin_post_path(@post.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger ml-2 px-3" %>
          </td>
        </tr>
      </table>
  </div>

  <div class='row-8'>
    <h5 class=" text-center mt-4">コメント</h5>
      <%= render "admin/post_comments/index", post: @post %>
  </div>

  <div class='row d-flex justify-content-center my-4'>
    <%= link_to '投稿一覧へ戻る', admin_posts_path, class: "btn btn-secondary" %>
  </div>
</div>