config/routes.rb
Rails.application.routes.draw do

  devise_scope :customer do
    post "public/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  # 顧客側ルーティング
  scope module: :public do
    scope '/customers' do
      get 'my_page/:id' => 'customers#show', as: 'mypage'
      get 'list' => 'customers#index', as: 'list'
      get 'information/edit' => 'customers#edit', as: 'edit_information'
      patch 'information' => 'customers#update', as: 'update_information'
      get 'unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
      patch 'withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    end

    resources :customers, only: [] do
      get :followings
      get :followers
      resource :relationships, only: [:create, :destroy]
      resources :favorites, only: [:index]
    end

    resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    post 'chats' => 'chats#create'
    get 'chats/room/:id' => 'chats#show', as: 'chat'
    get 'search', to: 'searches#search'
    resources :notifications, only: [:update]
  end

  # 管理者側ルーティング
  namespace :admin do
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :customers, only: [:index, :show, :edit, :update]
  end


end

app/views/layouts/_footer.html.erb
<footer class="<%= (admin_signed_in? ? "admin_footer" : "" ) %>">
  <nav class="navbar navbar-expand-lg", style="background-color: #bc8f8f; color: black;">
    <div class="mx-auto">
      <ul class="navbar-nav">
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_posts_path,class: 'nav-link text-dark ml-3' do %>
              <i class="fa-solid fa-file-image"></i>投稿一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_customers_path,class: 'nav-link text-dark ml-3' do %>
              <i class="fa-solid fa-user"></i>会員一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-dark ml-3' do %>
              <i class="fa-solid fa-right-from-bracket"></i>ログアウト
            <% end %>
          </li>
        <% elsif customer_signed_in? %>
          <li>
            <%= link_to mypage_path(current_customer.id),class: 'nav-link text-dark ml-5' do %>
              <i class="fa-solid fa-house"></i>
              <!--マイページ-->
            <% end %>
          </li>
          <li>
            <%= link_to posts_path,class: 'nav-link text-dark ml-5' do %>
              <i class="fa-regular fa-file-image"></i>
              <!--投稿一覧-->
            <% end %>
          </li>
          <li>
            <%= link_to list_path,class: 'nav-link text-dark ml-5' do %>
              <i class="fa-regular fa-user"></i>
              <!--会員一覧-->
            <% end %>
          </li>
          <li>
            <%= link_to customer_favorites_path(current_customer),class: 'nav-link text-dark ml-5' do %>
              <i class="fa-regular fa-heart"></i>
              <!--お気に入り一覧-->
            <% end %>
          </li>
          <li>
            <%= link_to new_post_path,class: 'nav-link text-dark ml-5' do %>
              <i class="fa-solid fa-file-pen"></i>
              <!--新規投稿-->
            <% end %>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-dark ml-5' do %>
              <i class="fa-solid fa-right-from-bracket"></i>
              <!--ログアウト-->
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_admin_session_path,class: 'nav-link text-dark ml-3' do %>
              <i class="fa-solid fa-user-tie"></i>管理者ログイン
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path,class: 'nav-link text-dark ml-3' do %>
              <i class="fa-solid fa-hands"></i>新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_session_path,class: 'nav-link text-dark ml-3' do %>
              <i class="fa-solid fa-right-to-bracket"></i>ログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header style="background-color: #bc8f8f; color: black;">
  <nav class="navbar navbar-expand-lg">
    <div class="mx-auto">
      <%= link_to (admin_signed_in? ? new_admin_session_path : root_path ), class: "logo" do %>
        <%= image_tag 'sharefashion.jpg', class: "rounded-circle", size: "100x100" %>
      <% end %>
    </div>
  </nav>
  <div class="d-flex justify-content-center pb-2">
    <% if customer_signed_in? %>
      <div class="dropdown mr-3">
        <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa-regular fa-bell"></i>
          <span class="badge badge-danger"><%= current_customer.notifications.where(read: false).count %></span>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <% if current_customer.notifications.where(read: false).any? %>
            <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
            <% current_customer.notifications.where(read: false).limit(5).order(created_at: :desc).each do |notification| %>
              <%= link_to notification_message(notification), notification_path(notification), method: :patch, class: "dropdown-item" %>
            <% end %>
          <% else %>
            <span class="dropdown-item disabled">未読の通知はありません</span>
          <% end %>
        </div>
      </div>
    <% end %>
    <%= render 'public/searches/form' %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>シェアファッション</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/5b87abe1b8.js" crossorigin="anonymous"></script>
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <main>
      <%= flash[:notice] %>
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>